#!/usr/bin/env bash


function noYMLFile (){
  echoColorText 'No config.yml present. Please make one.' 'Error: ' $RED
}


















function ymlCheck (){
  if [ -f ]; then
    $1
  else
    noYMLFile
  fi;
}

# Control flow
if [ $# -ne 0 ]; then
  for v in $#; do
    case ${1} in
      db)                   ymlCheck updateDB      shift;;
      setup)                ymlCheck setup ;       shift;;
      help|-h|--help)       helpText;              shift;;
      ""|*)                 helpText $i;           shift;;
    esac;
  done;
else
  helpText $1;
fi;
